add a "Accept a range argument" example from the docs (does not compile)
The compilation error is:

index.ts:28:7 - error TS2345: Argument of type '(range: any) => void' is not assignable to parameter of type '(...arg: any) => InterpreterValue'.
  Type 'void' is not assignable to type 'InterpreterValue'.

28       (range) => {
         ~~~~~~~~~~~~

index.ts:47:9 - error TS2322: Type '"RANGE"' is not assignable to type 'FunctionArgumentType'.

47       { argumentType: 'RANGE' },
           ~~~~~~~~~~~~

  node_modules/hyperformula/typings/interpreter/plugin/FunctionPlugin.d.ts:134:5
    134     argumentType: FunctionArgumentType;
            ~~~~~~~~~~~~
    The expected type comes from property 'argumentType' which is declared here on type 'FunctionArgument'

Found 2 errors in the same file, starting at: index.ts:28