paste example from the docs (does not compile)
The compilation error is:

index.ts:18:9 - error TS2322: Type '"STRING"' is not assignable to type 'FunctionArgumentType'.

18       { argumentType: "STRING" }
           ~~~~~~~~~~~~

  node_modules/hyperformula/typings/interpreter/plugin/FunctionPlugin.d.ts:134:5
    134     argumentType: FunctionArgumentType;
            ~~~~~~~~~~~~
    The expected type comes from property 'argumentType' which is declared here on type 'FunctionArgument'


Found 1 error in index.ts:18