paste translations from the docs (does not compile)
The compilation error is:

index.ts:23:16 - error TS2339: Property 'translations' does not exist on type 'typeof MyCustomPlugin'.

23 MyCustomPlugin.translations = {
                  ~~~~~~~~~~~~

Found 1 error in index.ts:23